---
apiVersion: v1
kind: Service
metadata:
  name: iblapi
  labels:
    app: iblapi-svc
spec:
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    app: iblapi
  type: ClusterIP
...
---
apiVersion: v1
kind: Service
metadata:
  name: ibl-node-server
  labels:
    app: ibl-node-server-svc
spec:
  ports:
  - port: 3333
    targetPort: 3333
  selector:
    app: ibl-node-server
  type: ClusterIP
...
---
apiVersion: v1
kind: Service
metadata:
  name: ibl-frontend
  labels:
    app: ibl-frontend-svc
spec:
  ports:
  - port: 9000
    targetPort: 9000
  selector:
    app: ibl-frontend
  type: ClusterIP
...
